name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 13
        uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install
      - run: npm run build --prefix client
